# Generated by Django 6.0 on 2026-01-14 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CB', 'CreateBooking'), ('RB', 'ReadBooking'), ('UB', 'UpdateBooking')], default='RB', help_text='Введіть назву дії', max_length=100, verbose_name='Дозволена дія')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Назва класу')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Опис класу')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введіть назву предмету', max_length=150, verbose_name='Назва предмета')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введіть назву посади', max_length=100, verbose_name='Посада')),
                ('actions', models.ManyToManyField(help_text='Виберіть дії, які можна виконувати', to='Profile.action', verbose_name='Список дозволів')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to='.', verbose_name='Аватарка')),
                ('bio', models.TextField(blank=True, default=None, null=True, verbose_name='Про себе')),
                ('phone_number', models.CharField(blank=True, default=None, help_text='Введіть номер телефону', max_length=20, null=True, verbose_name='Номер телефону')),
                ('class_room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.classroom')),
                ('positions', models.ManyToManyField(blank=True, default=None, null=True, to='Profile.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='subjects',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='Profile.subject', verbose_name='Список предметів'),
        ),
    ]
