# Generated by Django 6.0 on 2025-12-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default=None, help_text='Введіть номер телефону', max_length=20, null=True, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(choices=[('CB', 'CreateBooking'), ('RB', 'ReadBooking'), ('UB', 'UpdateBooking')], default='RB', help_text='Введіть назву дії', max_length=100, verbose_name='Дозволена дія'),
        ),
        migrations.AlterField(
            model_name='position',
            name='actions',
            field=models.ManyToManyField(help_text='Виберіть дії, які можна виконувати', to='Profile.action', verbose_name='Список дозволів'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(help_text='Введіть назву посади', max_length=100, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Введіть назву предмету', max_length=150, verbose_name='Назва предмета'),
        ),
    ]
