# Generated by Django 6.0 on 2026-02-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_profile_class_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='subjects',
            field=models.ManyToManyField(blank=True, default=None, to='Profile.subject', verbose_name='Список предметів'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='positions',
            field=models.ManyToManyField(blank=True, default=None, to='Profile.position'),
        ),
    ]
