# Generated by Django 6.0 on 2026-02-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_classroom_subjects_alter_profile_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(choices=[('CB', 'CreateBooking'), ('RB', 'ReadBooking'), ('UB', 'UpdateBooking'), ('CS', 'CreateSchedule'), ('RS', 'ReadSchedule')], default='RB', help_text='Введіть назву дії', max_length=100, verbose_name='Дозволена дія'),
        ),
    ]
